# frozen_string_literal: true
source 'http://rubygems.org'

gem 'thin'

gem 'rack'
gem 'rack-cors'

# TODO: revert to gem after mörge and release
gem 'grape', git: 'git@github.com:LeFnord/grape.git', branch: 'delete_204'
# gem 'grape', '~> 0.18'
gem 'grape-entity', '~> 0.6'
gem 'grape-swagger', '~> 0.25'
gem 'grape-swagger-entity', '~> 0.1.5'

group :development, :test do
  gem 'grape-starter'
  gem 'pry'
  gem 'rack-test'
  gem 'rake'
  gem 'rspec'
  gem 'rubocop'
end
