# frozen_string_literal: true

source 'http://rubygems.org'

gem 'thin'

gem 'rack'
gem 'rack-cors'

gem 'grape'
gem 'grape-entity'
gem 'grape-swagger'
gem 'grape-swagger-entity'

group :development, :test do
  gem 'grape-starter'
  gem 'pry'
  gem 'rack-test'
  gem 'rake'
  gem 'rspec'
  gem 'rubocop'
end
