inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/tmp/**/*'
    - '**/script/**/*'
    - '**/template/api/**'
    - grape-starter.gemspec
    - template/spec/spec-helper.rb
    - api/**/*
  UseCache: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Layout/IndentationWidth:
  Exclude:
    - 'lib/starter/builder/templates/files.rb'
    - 'lib/starter/builder/templates/endpoints.rb'

Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Naming/AccessorMethodName:
  Exclude:
    - 'lib/starter/builder/files.rb'
    - 'lib/starter/builder/endpoints.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false # to support ruby 3.0