#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

test -z "$RACK_ENV" &&
  RACK_ENV='development'

if [ "$RACK_ENV" = 'production' ]; then
  bundle exec thin start -p 9292 -e $RACK_ENV --tag api-starter -d --threaded
else
  bundle exec thin start -p 9292 -e $RACK_ENV --tag api-starter -V -D
fi
