#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

test -z "$RACK_ENV" &&
  RACK_ENV='development'

if [ $1 ]; then
  port=$1
else
  port=9292
fi

if [ "$RACK_ENV" = 'production' ]; then
  bundle exec thin start -p $port -e $RACK_ENV --tag {{{grape-starter}}} -d --threaded
else
  bundle exec thin start -p $port -e $RACK_ENV --tag {{{grape-starter}}} -V -D
fi
