#!/usr/bin/env sh

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "===> Running specs..."
if [ $1 ]; then
  bundle exec rspec $1
else
  bundle exec rspec
fi

echo "===> Running rubocop..."
bundle exec rake rubocop
