name: Pipeline
on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]
  push:
    branches:
      - 'master'

jobs:
  # pre-spec
  #
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop --parallel --format progress

  rspec:
    runs-on: ubuntu-latest
    needs: ['rubocop']
    env:
      RACK_ENV: test
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', head]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: create tmp dir
      run: mkdir tmp
    - name: Run rspec
      run: bundle exec rspec
